In [1]:
import numpy as np
import pandas as pd
from sklearn import datasets
from sklearn.model_selection import train_test_split

In [2]:
iris = datasets.load_iris()

In [4]:
X = iris['data'][:, (2,3)]
y = iris['target']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

In [5]:
iris_df = pd.DataFrame(X, columns=iris.feature_names[2:4])
iris_df['Species'] = y
iris_df.head()

petal length (cm)  petal width (cm)  Species
0                1.4               0.2        0
1                1.4               0.2        0
2                1.3               0.2        0
3                1.5               0.2        0
4                1.4               0.2        0

In [7]:
pd.Series(y).value_counts()

0    50
1    50
2    50
dtype: int64

In [8]:
from sklearn.linear_model import LogisticRegression
softmax_reg = LogisticRegression(multi_class='multinomial', C=10, random_state=42)
softmax_reg.fit(X_train, y_train)

LogisticRegression(C=10, multi_class='multinomial', random_state=42)

In [9]:
softmax_reg.predict(X_test)

array([2, 1, 0, 2, 0, 2, 0, 1, 1, 1, 2, 1, 1, 1, 1, 0, 1, 1, 0, 0, 2, 1,
       0, 0, 2, 0, 0, 1, 1, 0, 2, 1, 0, 2, 2, 1, 0, 2, 1, 1, 2, 0, 2, 0,
       0])

In [10]:
softmax_reg.predict_proba(X_test)[:5]

'''비교해보면, 이중에서 확률값이 높은게 기록되고 있음'''

array([[7.30211112e-08, 7.36092528e-03, 9.92639002e-01],
       [2.03607671e-03, 9.96770258e-01, 1.19366573e-03],
       [9.95315672e-01, 4.68432763e-03, 2.92178412e-12],
       [1.02343185e-10, 1.42787523e-03, 9.98572125e-01],
       [9.92805862e-01, 7.19413846e-03, 6.67228738e-12]])

In [11]:
np.argmax(softmax_reg.predict_proba([[3,2]]))
'''이때 array는 dim 2로 넣어줘야된당 (3,2)가 주어졌을때의 확률'''

1

In [12]:
softmax_reg.predict([[3,2]])

array([1])