In [1]:
import numpy as np

In [4]:
arr = np.array([4, 2, 0, 2, 9, 6, 0, 6, 16]).reshape(3,3)
np.linalg.eig(arr)


(array([ 2.8342777 ,  6.65462818, 19.51109412]),
 array([[-0.84206693, -0.53544397,  0.06498493],
        [ 0.4908081 , -0.71070233,  0.50399366],
        [-0.22367543,  0.45629153,  0.86125916]]))

In [8]:
from sklearn.decomposition import PCA

p = PCA(n_components=3)
p.fit_transform(arr)

p._


array([[-8.21220805e+00, -1.94470079e+00,  1.42805913e-16],
       [-5.42729341e-01,  3.54884964e+00,  1.42805913e-16],
       [ 8.75493739e+00, -1.60414884e+00,  1.42805913e-16]])

In [8]:
set = np.array([[1, 0.02, 0.96, 0.42, 0.01],
                [0.02, 1, 0.13, 0.71, 0.85],
                [0.96, 0.13, 1, 0.50, 0.11],
                [0.42, 0.71, 0.50, 1, 0.79],
                [0.01, 0.85, 0.11, 0.79, 1]])

set

array([[1.  , 0.02, 0.96, 0.42, 0.01],
       [0.02, 1.  , 0.13, 0.71, 0.85],
       [0.96, 0.13, 1.  , 0.5 , 0.11],
       [0.42, 0.71, 0.5 , 1.  , 0.79],
       [0.01, 0.85, 0.11, 0.79, 1.  ]])

In [25]:
eig_v = np.round(np.linalg.eigvalsh(set)[::-1], 3)
eig_v

array([2.853, 1.806, 0.204, 0.102, 0.034])

In [31]:
eig_matrix = np.round(np.linalg.eig(set)[1],3).T
eig_matrix

array([[-0.331, -0.46 , -0.382, -0.556, -0.473],
       [-0.607,  0.39 , -0.557,  0.078,  0.404],
       [ 0.702,  0.072, -0.709,  0.002,  0.009],
       [ 0.098,  0.743,  0.168, -0.602, -0.221],
       [ 0.139, -0.282,  0.117, -0.568,  0.751]])

In [35]:
eig_matrix.T

array([[-0.331, -0.607,  0.702,  0.098,  0.139],
       [-0.46 ,  0.39 ,  0.072,  0.743, -0.282],
       [-0.382, -0.557, -0.709,  0.168,  0.117],
       [-0.556,  0.078,  0.002, -0.602, -0.568],
       [-0.473,  0.404,  0.009, -0.221,  0.751]])

In [38]:
np.round(eig_v * eig_matrix,3)

array([[-0.944, -0.831, -0.078, -0.057, -0.016],
       [-1.732,  0.704, -0.114,  0.008,  0.014],
       [ 2.003,  0.13 , -0.145,  0.   ,  0.   ],
       [ 0.28 ,  1.342,  0.034, -0.061, -0.008],
       [ 0.397, -0.509,  0.024, -0.058,  0.026]])

In [36]:
eig_v**0.5 @ eig_matrix.T

array([-1.61459338, -0.65333338,  0.96456376,  1.00689493, -0.13427272])

In [33]:
((eig_v ** 0.5) @ eig_matrix) * ((eig_v**0.5) eig_matrix.T)

array([-1.00082159, -0.03505003, -1.63876878, -1.13040175, -0.18404978])